### ISSUE TITLE
month and year implementation

### ISSUE THREAD

**Issue by mehulpamale** [nixrajput/get-time-ago#20]
Do we have month and year implementation?

**Comment by nixrajput** [comment]
Hi @mehulpamale,

No, we don't have that implementation right now.

This package is made for converting DateTime into days ago. If the DateTime exceeds 7 days, It displays the Date and Time in the provided format.

`timeago` package includes that feature you are asking for. So I don't think we should implement that feature in this package.

I will listen to more views and opinions on this topic before deciding whether to implement it or not.

Thanks,
Nikhil
